services:
    app.event_listener.session_initializer:
        class: App\EventListener\SessionInitializer
        arguments: ['@app.security.session']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.event_listener.cors_header_sender:
        class: App\EventListener\CorsHeader
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10000 }
            - { name: kernel.event_listener, event: kernel.response, priority: 10000 }

    app.event_listener.session_saver:
        class: App\EventListener\SessionSaver
        arguments: ['@app.security.session']
        tags:
            - { name: kernel.event_listener, event: kernel.response }
