services:
    app.event_listener.cors_header_sender:
        class: App\EventListener\CorsHeader
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10000 }
            - { name: kernel.event_listener, event: kernel.response, priority: 10000 }

    app.event_listener.profiler:
        class: App\EventListener\DebugTokenLogger
        arguments:
            - '@app.logger'
            - '%kernel.environment%'
        tags:
             - { name: kernel.event_listener, event: kernel.terminate }

    app.event_listener.token_regenerator:
        class: App\EventListener\TokenRegeneration
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
             - { name: kernel.event_listener, event: kernel.response }
