services:
    app.security.token_authenticator:
        class: App\Service\Authentication\TokenAuthenticator
        arguments:
            - '@app.security.token_manager'
            - '%kernel.environment%'

    app.security.token_manager:
        class: App\Service\Authentication\TokenManager
        arguments:
            - '@doctrine.orm.default_entity_manager'

    app.security.authentication_manager:
        public: true
        class: App\Service\Authentication\AuthenticationManager
        arguments:
            - '@app.security.token_manager'
            - '@security.token_storage'
