services:
    app.security.token_authenticator:
        class: App\Service\Authentication\TokenAuthenticator
        arguments:
            - '@app.security.token_provider'
            - '@doctrine.orm.default_entity_manager'
            - '%kernel.environment%'

    app.security.token_provider:
        class: App\Service\Authentication\TokenProvider
        arguments:
            - '@request_stack'
            - '@doctrine.orm.default_entity_manager'

    app.security.user_by_token_provider:
        class: App\Service\Authentication\UserByTokenProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    app.security.authentication_manager:
        public: true
        class: App\Service\Authentication\AuthenticationManager
        arguments:
            - '@security.token_storage'
            - '@app.security.token_provider'
