security:
    providers:
        in_memory: { memory: ~ }

        user_by_email:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_by_email
            guard:
                authenticators: ['app.security.token_authenticator']

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
