# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

imports:
    - { resource: 'services/default.yaml' }
    - { resource: 'services/security.yaml' }
    - { resource: 'services/event_listener.yaml' }
    - { resource: 'services/factory.yaml' }

services:
    app.service.exchange_rate_parser:
        class: App\Service\BankReport\ExchangeRateParser

    app.service.exchange_rate_provider:
        class: App\Service\BankReport\ExchangeRateProvider
        arguments:
          - '@doctrine.orm.default_entity_manager'
          - '@app.service.exchange_rate_parser'

    app.service.bank_report_parser:
        class: App\Service\BankReport\Parser
        arguments:
          - '@doctrine.orm.default_entity_manager'
