# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

imports:
    - { resource: 'services/default.yaml' }
    - { resource: 'services/security.yaml' }
    - { resource: 'services/event_listener.yaml' }
    - { resource: 'services/factory.yaml' }
    - { resource: 'services/elastica.yaml' }

services:
    app.service.exchange_rate_parser:
        class: App\Service\BankReport\ExchangeRateParser
        arguments:
            - '@logger'

    app.service.exchange_rate_provider:
        class: App\Service\BankReport\ExchangeRateProvider
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@app.service.exchange_rate_parser'

    app.service.bank_report_parser:
        class: App\Service\BankReport\Parser
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@app.factory.currency_converter'
            - '@security.token_storage'

    app.logger:
        class: App\Service\Log\Logger
        public: true
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@logger'
            - '@security.token_storage'
            - '%env(SLACK_FRONTEND_USER_IDS)%'
            - '%env(SLACK_BACKEND_USER_IDS)%'

    app.monolog.mention_formatter:
        class: App\Service\Log\MentionFormatter
        arguments:
            - '%env(SLACK_FRONTEND_USER_IDS)%'
            - '%env(SLACK_BACKEND_USER_IDS)%'
        tags:
            - { name: monolog.processor, handler: slack_notification }
